apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodeapp
  name: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodeapp
    spec:
      containers:
      - image: gcr.io/wideops-candidate6/omar-nodeapp:test
        name: nodeapp
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 80 
status: {}
---