apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodeapp-ingress
spec:
  defaultBackend:
    service:
      name: nodeapp
      port:
        number: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tls-ingress
spec:
  tls:
  - hosts:
    - omar-nodeapp.com
    secretName: test-tls
  rules:
    - host: omar-nodeapp.com
      http:
        paths:
        - path: /
          backend:
            serviceName: nodeapp
            servicePort: 80