apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cer
spec:
  domains:
    - sec.omar-nodeapp.com

---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-secure
spec:
  selector:
    app: nodeapp
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000

