apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
spec:
  domains:
    - omar-nodeapp.com

---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-secure
spec:
  selector:
    app: nodeapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3000

